# Generated by Django 5.2.5 on 2026-04-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_chapter_users(apps, schema_editor):
    Chapter = apps.get_model("chapters", "Chapter")
    CustomUser = apps.get_model("users", "CustomUser")
    db_alias = schema_editor.connection.alias

    missing_user_qs = Chapter.objects.using(db_alias).filter(user__isnull=True)
    if not missing_user_qs.exists():
        return

    fallback_email = "legacy-migration-user@invalid.local"
    fallback_user = (
        CustomUser.objects.using(db_alias).filter(email=fallback_email).first()
    )
    if fallback_user is not None and fallback_user.is_active:
        raise RuntimeError(
            "The reserved legacy migration user already exists and is active. "
            "Resolve that account before migrating legacy chapters."
        )
    if fallback_user is None:
        if CustomUser.objects.using(db_alias).filter(
            username="legacy_migration_user"
        ).exists():
            raise RuntimeError(
                "The reserved legacy migration username already exists. "
                "Resolve that account before migrating legacy chapters."
            )
        fallback_user = CustomUser.objects.using(db_alias).create(
            username="legacy_migration_user",
            email=fallback_email,
            is_active=False,
            password="!",
        )

    missing_user_qs.update(user_id=fallback_user.id)


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="category",
            field=models.CharField(default="Uncategorized", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chapter",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chapter",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(backfill_chapter_users, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="chapter",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
