# Generated by Django 5.2.4 on 2026-08-10 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0002_add_category_user_and_soft_delete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(
                fields=["user", "is_deleted", "-created_at"],
                name="chap_user_del_created_idx",
            ),
        ),
    ]
