"""
AI utility functions for quiz/question generation.
Includes prompt building, schema definitions, and model-calling functions for AI model responses.
"""

import json
from google import genai
from django.conf import settings
from typing import List, Literal
from pydantic import BaseModel
import logging
from time import sleep

# Models for the AI response
class Choice(BaseModel):
    """
    Represents a possible answer choice for a question.
    Attributes:
        text (str): The text of the choice.
        is_correct (bool): Whether this choice is correct.
    """
    text: str
    is_correct: bool

class Question(BaseModel):
    """
    Represents a quiz question generated by the AI.
    Attributes:
        question_text (str): The text of the question.
        question_type (Literal): The type of question (MCQ, MRQ, TF).
        choices (List[Choice]): List of possible answer choices.
    """
    question_text: str
    question_type: Literal["MCQ", "MRQ", "TF"]
    choices: List[Choice]

class ChapterContent(BaseModel):
    """
    Represents the summary content of a chapter.
    Attributes:
        title (str): The title of the chapter.
        description (str): The summary description of the chapter.
    """
    title: str
    description: str

class ChapterSchema(BaseModel):
    """
    Represents the full AI response schema, including chapter summary and questions.
    Attributes:
        chapter (ChapterContent): The chapter summary.
        questions (List[Question]): List of generated questions.
    """
    chapter: ChapterContent
    questions: List[Question]

BASE_INSTRUCTIONS = """
You are an expert quiz generator and a helpful assistant that creates questions from lecture or textbook content.

Your tasks:
1. Write a concise **summary of the chapter content** (3–5 sentences), highlighting the most important definitions, formulas, concepts, processes, and examples.
2. Generate **exactly 10-15 quiz questions** strictly based on the core learning material in the chapter. Cover all key points, ensuring that each major topic has at least one question.

Question Types & Rules:
- **MCQ (Multiple Choice Question)**: 3–4 options, exactly one correct answer.
- **MRQ (Multi Response Question)**: 3–4 options, one or more correct answers.
- **TF (True/False)**: Only two options (True, False), exactly one correct answer.
- Ensure **diversity**: approximately 50% MCQs, 25% MRQs, 25% TFs, unless the content is unsuitable.
- Choices must be **plausible** and non-trivial; avoid obviously wrong answers or jokes.

Content Coverage:
- Focus **only** on lecture or textbook content.
- Include definitions, formulas, key concepts, processes, examples, and comparisons.
- Ignore: administrative info (exam dates, office hours, announcements), section dividers (e.g., "Summary", "Questions?"), references, citations, URLs, and image captions without context.
- Ignore course descriptions, motivations, or learning objectives.
"""

logger = logging.getLogger(__name__)

# Priorty order for trying Gemini models
MODEL_CHAIN = [
    "gemini-2.5-flash",
    "gemini-2.5-pro",
    "gemini-2.5-flash-lite",
]
OVERLOAD_MARKERS = ("unavailable", "overloaded", "503")

def build_user_prompt(chapter_title: str, chapter_content: str) -> str:
    """
    Build a prompt string to send to the AI model for quiz/question generation.

    Args:
        chapter_title (str): The title of the chapter.
        chapter_content (str): The full text content of the chapter.

    Returns:
        str: The formatted prompt for the AI model.
    """

    return f"""
      <chapter_title>
      {chapter_title}
      </chapter_title>

      <chapter_content>
      {chapter_content}
      </chapter_content>
      """
    
def call_gemini_model(chapter_title: str, chapter_content: str, *, max_retries_per_model: int = 2, base_backoff: float = 0.75) -> dict:
    """Try Gemini models in order with retry/fallback. Returns parsed JSON."""
    prompt = build_user_prompt(chapter_title, chapter_content)
    client = genai.Client(api_key=settings.GEMINI_API_KEY)

    last_err = None
    for model in MODEL_CHAIN:
        for attempt in range(max_retries_per_model):
            try:
                logger.info("[Gemini] %s attempt %d", model, attempt + 1)
                resp = client.models.generate_content(
                    model=model,
                    contents=prompt,
                    config={
                        "response_mime_type": "application/json",
                        "response_schema": ChapterSchema,
                    },
                )
                txt = resp.candidates[0].content.parts[0].text
                data = json.loads(txt)
                data["_model_used"] = model
                return data
            except Exception as e:  # keep broad; upstream lib raises custom errors
                msg = str(e)
                is_overload = any(m in msg.lower() for m in OVERLOAD_MARKERS)
                logger.warning("[Gemini] %s failed (overload=%s): %s", model, is_overload, msg)
                last_err = e
                if is_overload and attempt < max_retries_per_model - 1:
                    sleep(base_backoff * (2 ** attempt))
                    continue  # retry same model
                if is_overload:  # move to next model
                    break
                # Non-overload error: bubble up immediately
                raise
        # next model
    raise RuntimeError(f"Gemini models unavailable: {last_err}")