# Generated by Django 5.2.4 on 2026-08-10 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attempts", "0002_attempt_constraints_indexes_related_names"),
        ("chapters", "0003_chapter_chap_user_del_created_idx"),
        ("questions", "0002_choice_choice_question_id_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapterattempt",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="attempts",
                to="chapters.chapter",
            ),
        ),
        migrations.AlterField(
            model_name="questionattempt",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="question_attempts",
                to="questions.question",
            ),
        ),
    ]
