# Generated by Django 5.2.4 on 2026-08-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0003_chapter_chap_user_del_created_idx"),
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="choice",
            index=models.Index(
                fields=["question", "id"], name="choice_question_id_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["chapter", "id"], name="question_chapter_id_idx"
            ),
        ),
    ]
