# Generated by Django 5.2.4 on 2026-08-10

import django.db.models.functions.text
from django.db import migrations, models


def normalize_existing_emails(apps, schema_editor):
    user_model = apps.get_model("users", "CustomUser")
    database = schema_editor.connection.alias
    duplicates = (
        user_model.objects.using(database)
        .annotate(normalized_email=django.db.models.functions.text.Lower("email"))
        .values("normalized_email")
        .annotate(total=models.Count("id"))
        .filter(total__gt=1)
    )
    if duplicates.exists():
        raise RuntimeError(
            "Case-insensitive duplicate user emails must be resolved before migrating."
        )
    for user in user_model.objects.using(database).only("id", "email").iterator():
        normalized = user.email.strip().lower()
        if normalized != user.email:
            user_model.objects.using(database).filter(pk=user.pk).update(email=normalized)


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(normalize_existing_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="unique_user_email_ci",
            ),
        ),
    ]
